### ISSUE TITLE
给 `ping` 增加限制参数

### ISSUE THREAD

**Issue by PragmaTwice** [CoderiGenius/QUST-Reconnector#2]
https://github.com/CoderiGenius/QUST-Reconnector/blob/master/Reconnect.go#L90

在 linux 下这个命令感觉会一直跑个不停啊

windows 下是默认发 4 个 icmp 包就会停掉然后统计结果，linux 下是一直发除非人为给一个 SIGINT 之类的信号才会停

建议在 linux 下替换为 `ping -c 4 host`，这样发 4 个包就会停下来了..

**Comment by CoderiGenius** [comment]
了解了，这里写的不够严谨，本质目的是不停的对外ping，然而windows下我写的是用for死循环，而linux下没有考虑到不会退出，下一个版本修改，感谢提交issue

**Comment by CoderiGenius** [comment]
![image](https://user-images.githubusercontent.com/29704758/52853932-fb53ce00-3157-11e9-867f-fe755d1506f6.png)
已修改
